services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "bin/rails db:prepare && bin/rails s -b 0.0.0.0"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/rails:cached
